FROM openjdk:17-alpine
ARG JAR_FILE=build/libs/coverflow-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar
ENV SPRING_PROFILES_ACTIVE=prod
ENTRYPOINT ["java","-jar", "-Dspring.profiles.active=prod", "/app.jar"]